apiVersion: apps/v1
kind: Deployment
metadata:
  name: framework-educativo-zuul
  labels:
    app: framework-educativo-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framework-educativo-zuul
  template:
    metadata:
      labels:
        app: framework-educativo-zuul
    spec:
      containers:
        - name: framework-educativo-zuul
          image: tronxi/framework-educativo-zuul:${ZUUL_TAG}
          resources:
            limits:
              cpu: "0.3"
              memory: "300Mi"
            requests:
              cpu: "0.2"
              memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8070
            initialDelaySeconds: 90
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8070
            initialDelaySeconds: 90
            periodSeconds: 30
          env:
            - name: profile
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: profile
            - name: clave
              valueFrom:
                secretKeyRef:
                  name: framework-educativo-secret
                  key: clave
            - name: eureka_host
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: eureka_host
            - name: zuul_service
              valueFrom:
                configMapKeyRef:
                  name: framework-educativo-config-map
                  key: zuul_service

---
apiVersion: v1
kind: Service
metadata:
  name: zuul-service
  labels:
    app: framework-educativo-zuul
spec:
  type: NodePort
  selector:
    app: framework-educativo-zuul
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070