spring:
  application:
    name: "swagger"
#  cloud:
#    client:
#      hostname: raspberrytronxi3.ddns.net
server:
  port: 8070
eureka-host: http://localhost
eureka:
  instance:
    status-page-url-path: /swagger-ui.html
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka-host}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
